version: '2'
services:
  proxy:
    build:
      context: ./
      dockerfile: ./proxy/dev.proxy.dockerfile
    ports:
      - "443:443"
    links:
      - "devserver:devserver"
      - "ssrserver:ssrserver"
    volumes:
      - ./static:/usr/src/app
  devserver:
    build:
      context: ./
      dockerfile: ./src/client/client.dockerfile
    volumes:
      - ./src/client:/usr/src/app/src/client
  ssrserver:
    build:
      context: ./
      dockerfile: ./src/server/devssr.dockerfile
    volumes:
      - ./src:/usr/src/app/src
