version: '2'
services:
  proxy:
    build:
      context: ./
      dockerfile: ./proxy/dev.proxy.dockerfile
    ports:
      - "443:443"
    links:
      - "webserver:webserver"
  webserver:
    build:
      context: ./
      dockerfile: ./src/server/server.dockerfile
    ports:
      - "80:80"
