version: '2'
services:
  proxy:
    build:
      context: ./
      dockerfile: ./proxy/dev.proxy.dockerfile
    ports:
      - "443:443"
    links:
      - "uiserver:uiserver"
      - "ssrserver:ssrserver"
    volumes:
      - ./src/static:/usr/src/app
  uiserver:
    build:
      context: ./
      dockerfile: ./src/ui/ui.dockerfile
    volumes:
      - ./src/ui:/usr/src/app/src/ui
  ssrserver:
    build:
      context: ./
      dockerfile: ./src/ssr/devssr.dockerfile
    volumes:
      - ./src/ui:/usr/src/app/src/ui
      - ./src/ssr:/usr/src/app/src/ssr
