version: '2'
services:
  proxy:
    build:
      context: ./
      dockerfile: ./proxy/static.proxy.dockerfile
    ports:
      - "443:443"
    links:
      - "ssrserver:ssrserver"
  ssrserver:
    build:
      context: ./
      dockerfile: ./src/ssr/prodssr.dockerfile
