#!/bin/sh
# thanks to https://www.hackzine.org/using-https-with-self-signed-certificate-in-nginx.html
PASSWORD=Password1
CERTDETAILS="/C=GB/ST=London/L=London/O=Site Seed International/OU=Site Seed/CN=local.siteseed.com"
mkdir ./proxy/cert/ca 2> /dev/null
cd ./proxy/cert/ca
rm -f ca.* ia.* 2> /dev/null
openssl genrsa -des3 -out ca.orig.key -passout pass:$PASSWORD 4096
openssl rsa -in ca.orig.key -out ca.key -passin pass:$PASSWORD
rm ca.orig.key
openssl req -new -x509 -days 365 -key ca.key -out ca.crt -subj "$CERTDETAILS"
echo 01 > ca.srl
openssl genrsa -des3 -out ia.key -passout pass:$PASSWORD 4096
openssl req -new -key ia.key -out ia.csr -passin pass:$PASSWORD -subj "$CERTDETAILS"
openssl x509 -req -days 730 -in ia.csr -CA ca.crt -CAkey ca.key -out ia.crt
echo 01 > ia.srl
cd ../../..
